import { useCallback } from "react";

export default function ExportPanel({ script, nodes, edges }: any) {
  const downloadScript = useCallback(() => {
    const element = document.createElement("a");
    const file = new Blob([script], { type: "text/plain" });
    element.href = URL.createObjectURL(file);
    element.download = "script.sh";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  }, [script]);

  const downloadCanvasLayout = useCallback(() => {
    const layout = { nodes, edges };
    const element = document.createElement("a");
    const file = new Blob([JSON.stringify(layout, null, 2)], { type: "application/json" });
    element.href = URL.createObjectURL(file);
    element.download = "shell-y-layout.json";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  }, [nodes, edges]);

  const downloadDocumentation = useCallback(() => {
    const doc = `# Shell Script Documentation

## Generated by Shell-y

### Overview
This is a shell script generated using the Shell-y visual builder.

### Commands Used
${nodes
  .filter((n: any) => n.type === "command")
  .map((n: any) => `- ${n.data.label}`)
  .join("\n")}

### Full Script
\`\`\`bash
${script}
\`\`\`

### How to Use
1. Save the script to a file with \`.sh\` extension
2. Make it executable: \`chmod +x script.sh\`
3. Run it: \`./script.sh\`

---
Generated by Shell-y on ${new Date().toLocaleString()}
`;

    const element = document.createElement("a");
    const file = new Blob([doc], { type: "text/markdown" });
    element.href = URL.createObjectURL(file);
    element.download = "README.md";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  }, [script, nodes]);

  const buttonStyle = {
    flex: 1,
    padding: "8px 12px",
    borderRadius: 8,
    border: "1px solid #1e293b",
    background: "#020617",
    color: "white",
    cursor: "pointer",
    fontSize: 12,
    transition: "all 0.2s"
  };

  return (
    <div
      style={{
        display: "flex",
        gap: 8,
        marginTop: 12,
        paddingTop: 12,
        borderTop: "1px solid #1e293b"
      }}
    >
      <button
        onClick={downloadScript}
        title="Download as .sh file"
        style={buttonStyle}
        onMouseEnter={(e) => (e.currentTarget.style.borderColor = "#7c3aed")}
        onMouseLeave={(e) => (e.currentTarget.style.borderColor = "#1e293b")}
      >
        📥 Script
      </button>
      <button
        onClick={downloadCanvasLayout}
        title="Save canvas layout for later editing"
        style={buttonStyle}
        onMouseEnter={(e) => (e.currentTarget.style.borderColor = "#7c3aed")}
        onMouseLeave={(e) => (e.currentTarget.style.borderColor = "#1e293b")}
      >
        💾 Layout
      </button>
      <button
        onClick={downloadDocumentation}
        title="Download README documentation"
        style={buttonStyle}
        onMouseEnter={(e) => (e.currentTarget.style.borderColor = "#7c3aed")}
        onMouseLeave={(e) => (e.currentTarget.style.borderColor = "#1e293b")}
      >
        📚 Docs
      </button>
    </div>
  );
}
