import { useCallback, useRef } from "react";

export default function ExportPanel({ script, nodes, edges, onLoadLayout }: any) {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const downloadScript = useCallback(() => {
    const element = document.createElement("a");
    const file = new Blob([script], { type: "text/plain" });
    element.href = URL.createObjectURL(file);
    element.download = "script.sh";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  }, [script]);

  const downloadCanvasLayout = useCallback(() => {
    const layout = { nodes, edges };
    const element = document.createElement("a");
    const file = new Blob([JSON.stringify(layout, null, 2)], { type: "application/json" });
    element.href = URL.createObjectURL(file);
    element.download = "shell-y-layout.json";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  }, [nodes, edges]);

  const downloadDocumentation = useCallback(() => {
    const doc = `# Shell Script Documentation

## Generated by Shell-y

### Overview
This is a shell script generated using the Shell-y visual builder.

### Commands Used
${nodes
  .filter((n: any) => n.type === "command")
  .map((n: any) => `- ${n.data.label}`)
  .join("\n")}

### Full Script
\`\`\`bash
${script}
\`\`\`

### How to Use
1. Save the script to a file with \`.sh\` extension
2. Make it executable: \`chmod +x script.sh\`
3. Run it: \`./script.sh\`

---
Generated by Shell-y on ${new Date().toLocaleString()}
`;

    const element = document.createElement("a");
    const file = new Blob([doc], { type: "text/markdown" });
    element.href = URL.createObjectURL(file);
    element.download = "README.md";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  }, [script, nodes]);

  const buttonStyle = {
    width: "100%",
    padding: "8px 12px",
    borderRadius: 6,
    border: "1px solid #333",
    background: "#000",
    color: "white",
    cursor: "pointer",
    fontSize: 12,
    transition: "all 0.2s",
    textAlign: "left" as const
  };

  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        gap: 6,
        marginTop: 12,
        paddingTop: 12,
        borderTop: "1px solid #333"
      }}
    >
      <button
        onClick={downloadScript}
        title="Download as .sh file"
        style={buttonStyle}
        onMouseEnter={(e) => (e.currentTarget.style.borderColor = "#666")}
        onMouseLeave={(e) => (e.currentTarget.style.borderColor = "#333")}
      >
        📥 Download Script
      </button>
      <div style={{ display: "flex", gap: 6 }}>
        <button
          onClick={downloadCanvasLayout}
          title="Save canvas layout for later editing"
          style={{ ...buttonStyle, flex: 1 }}
          onMouseEnter={(e) => (e.currentTarget.style.borderColor = "#666")}
          onMouseLeave={(e) => (e.currentTarget.style.borderColor = "#333")}
        >
          💾 Save
        </button>
        <button
          onClick={() => fileInputRef.current?.click()}
          title="Load a previously saved canvas layout"
          style={{ ...buttonStyle, flex: 1 }}
          onMouseEnter={(e) => (e.currentTarget.style.borderColor = "#666")}
          onMouseLeave={(e) => (e.currentTarget.style.borderColor = "#333")}
        >
          📂 Load
        </button>
        <input
          ref={fileInputRef}
          type="file"
          accept=".json"
          style={{ display: "none" }}
          onChange={(e) => {
            const file = e.target.files?.[0];
            if (!file) return;
            const reader = new FileReader();
            reader.onload = () => {
              try {
                const layout = JSON.parse(reader.result as string);
                if (layout.nodes && layout.edges) {
                  onLoadLayout?.(layout);
                }
              } catch {
                alert("Invalid layout file");
              }
            };
            reader.readAsText(file);
            // Reset so the same file can be loaded again
            e.target.value = "";
          }}
        />
      </div>
      <button
        onClick={downloadDocumentation}
        title="Download README documentation"
        style={buttonStyle}
        onMouseEnter={(e) => (e.currentTarget.style.borderColor = "#666")}
        onMouseLeave={(e) => (e.currentTarget.style.borderColor = "#333")}
      >
        📚 Generate Docs
      </button>
    </div>
  );
}
